### ISSUE TITLE
Can't export to image file

### ISSUE THREAD

**Issue by stardiviner** [metasoarous/oz#50] opened 2019-02-14 06:31 UTC
I checked out `oz/export!` docstring. It's experimental. But it says support jpg image exporting.
I tried, but get error:
```clojure
(require '[oz.core :as vega])

(defn group-data [& names]
     (apply concat (for [n names]
                     (map-indexed (fn [i x] {:x i :y x :col n})
                                  (take 20 (repeatedly #(rand-int 100)))))))

(def line-plot
  {:data {:values (group-data "monkey" "slipper" "broom")}
   :encoding {:x {:field "x"}
              :y {:field "y"}
              :color {:field "col" :type "nominal"}}
   :mark "line"})

(vega/export! line-plot "chart.jpg")
(vega/export! line-plot "chart.jpg" {:as :jpg})
```

I really hope Oz can support image exporting.

**Comment by metasoarous** [comment] 2019-02-14 08:19
Hi @stardiviner. Thanks for reporting.

I believe the docstring says

>  Export spec to an html file. May have other options, including svg, jpg & pdf available

I probably should have written "May _eventually_ have...", as that was the intended meaning. Sorry to let you down there. I'll update that in the next release.

In any caes, there is already an issue for this over at #36. If you would like, please feel free to follow or show your support for that issue. You may also wish to take a look at these comments: https://github.com/metasoarous/oz/issues/5#issuecomment-446080109, if you're interested in helping with this.

For now I'm going to close this issue as a duplicate, but thanks again for your feedback.

**Closed by metasoarous** 2019-02-14 08:19 UTC

**Comment by metasoarous** [comment] 2020-11-16 08:23
Please note that #36 has now been resolved, and you can export to `jpg` or `svg` as intended above.

Thanks again for posting @stardiviner!

**Comment by stardiviner** [comment] 2020-11-16 09:27
Thanks @metasoarous , That's great! 😄
