### ISSUE TITLE
:sort key does not result in bar chart data being sorted

### ISSUE THREAD

**Issue by ben741** [metasoarous/oz#67] opened 2019-05-31 12:10 UTC
Thanks for creating this library! I've been able to make some neat visualizations, and I'm really enjoying the experience so far. 

However, I'm seeing an issue with sorting both in the REPL and clojupyter. Here's the code for clojupyter:

```(require '[clojupyter.misc.helper :as helper])
(require '[clojupyter.misc.helper :as helper])
(helper/add-dependencies '[metasoarous/oz "1.6.0-alpha2"])

(require '[oz.notebook.clojupyter :as oz])

(def h-bar
  {:data {:values [{:name "a" :val 2}
                   {:name "c" :val 1}
                   {:name "b" :val 3}]}
    :mark "bar"
    :encoding {:y {:field "name"
                   :type :ordinal
                   :sort {:encoding :x
                          :order :descending}}
              :x {:field "val"
                  :type "quantitative"}}})

(oz/view! h-bar)
```
And the resulting plot:
<img width="393" alt="clojupyter-h-bar" src="https://user-images.githubusercontent.com/2756083/58702831-e0a70d00-8374-11e9-8a88-c97229baa913.png">

If I click the three dots and open it in the Vega-lite editor (Vega-lite version 3.0), I get the expected plot with data sorted.
<img width="269" alt="vega-lite-editor-h-bar" src="https://user-images.githubusercontent.com/2756083/58702883-059b8000-8375-11e9-82a9-37a84ffb31c8.png">

Additional notes:
- Adding the `:sort` key does change the order away from the default (which was a,b,c), but not in a way that I understand what it thinks its sorting by
- I also saw this in 1.5.6
- I've tried some other variations of `:sort`, from the vega-lite examples, but haven't found any that work
- I'm not running in Docker. 
- I saw the same behavior in Firefox and Chrome.
- The web console in my clojupyter tab warns "The compiled spec uses Vega v3, but current version is 4.4.0." every time I call `oz/view!`

Using the REPL, I get the following in the web console on localhost:
<img width="552" alt="vega-lite-web-console" src="https://user-images.githubusercontent.com/2756083/58703910-392bd980-8378-11e9-89e0-a2c78c9ca6c7.png">

Perhaps notably, when I switch the Vega-lite editor to Vega it goes to Vega v5, so perhaps the problem is whether it uses Vega v4 or v5?

**Comment by ben741** [comment] 2019-06-05 11:52
Updates:
- still seeing the same incorrectly sorted plot as above in clojupyter notebook on `'[metasoarous/oz "1.6.0-alpha2"]`
- in the REPL, 1.6.0-alpha3 now uses vega v5 and plots the bars in the sorted order I'd expect (yay!). For some reason, going back to 1.6.0-alpha2 has also decided to use vega v5, which is a bit puzzling
- in clojupyter notebook with `'[metasoarous/oz "1.6.0-alpha3"]`, `oz/view!` now errors out with 
```
Error printing return value (IllegalStateException) at clojure.lang.Var/pushThreadBindings (Var.java:325).
Can't dynamically bind non-dynamic var: hiccup.util/*escape-strings?*

            Var.java:   325 clojure.lang.Var/pushThreadBindings                                       
            core.clj:  1929 clojure.core$push_thread_bindings/invokeStatic                            
            core.clj:  1913 clojure.core$push_thread_bindings/invoke                                  
      clojupyter.clj:    99 oz.notebook.clojupyter$view_BANG_$reify__22211/to_mime                    
nrepl_middleware.clj:    21 clojupyter.kernel.cljsrv.nrepl_middleware$mime_values$fn$reify__12644/send
            main.clj:   419 clojure.main$repl$read_eval_print__9068/invoke                            
            main.clj:   435 clojure.main$repl$fn__9077/invoke                                         
            main.clj:   345 clojure.main$repl/doInvoke                                                
         RestFn.java:  1523 clojure.lang.RestFn/invoke                                                
            AFn.java:    22 clojure.lang.AFn/run                                                      
            AFn.java:    22 clojure.lang.AFn/run                                                      
         Thread.java:   844 java.lang.Thread/run                                                      
```

**Comment by metasoarous** [comment] 2019-06-05 18:15
Hi @ben741. Thanks for your report. Glad that the 1.6.0-alpha3 changes at least partially fixed things. Sorry to hear about the clojupyter issues however. I'm going to create a separate issue for that.

**Comment by ben741** [comment] 2019-06-06 11:11
Thanks for following up, and I agree these are separate issues. I checked out the code (at release 1.6.0-alpha3 a83d4b...), and was able to fix the sort problem by changing `require-string` to use `'vega-lite': 'vega-lite@3?noext',` (instead of `@2`) here:
https://github.com/metasoarous/oz/blob/master/src/clj/oz/notebook/clojupyter.clj#L22

**Comment by metasoarous** [comment] 2019-06-07 21:44
Oh, great! Good catch. I really need to have more unified flow of versions through the code. Right now, I think I end up having to specify in 4 different places (the `bin/update-cljsjs.sh` script, the `project.clj`, the `oz.core` export code, and the notebook code), which is obviously silly. Would be nice to unify that so updates like this don't slip through the cracks. Hmm... :thinking:

**Comment by MawiraIke** [comment] 2020-01-07 21:17
Thanks for the library, I love the visualizations and capabilities of Oz.

> Oh, great! Good catch. I really need to have more unified flow of versions through the code. Right now, I think I end up having to specify in 4 different places (the `bin/update-cljsjs.sh` script, the `project.clj`, the `oz.core` export code, and the notebook code), which is obviously silly. Would be nice to unify that so updates like this don't slip through the cracks. Hmm...

About this, I haven't got an issue but I realize that the current versions in clojupyter are different from the ones in oz.core and project.clj.
Clojupyter:
```
'vega-embed':  'vega-embed@3?noext',
'vega-lib': 'vega-lib?noext',
'vega-lite': 'vega-lite@2?noext',
'vega': 'vega@3?noext'
```
oz.core for example:
```clojure
(def vega-version "5.4.0")
(def vega-lite-version "3.4.0")
(def vega-embed-version "4.4.0")
```
Is this intentional or did it slip through?

**Comment by MawiraIke** [comment] 2020-05-30 14:42
> Thanks for following up, and I agree these are separate issues. I checked out the code (at release 1.6.0-alpha3 a83d4b...), and was able to fix the sort problem by changing `require-string` to use `'vega-lite': 'vega-lite@3?noext',` (instead of `@2`) here:
> https://github.com/metasoarous/oz/blob/master/src/clj/oz/notebook/clojupyter.clj#L22

Seems like this issue might be fixed with the changes made to fix [this other issue](https://github.com/metasoarous/oz/issues/91). I can't reproduce the error but get a sorted graph with no error messages.

**Comment by metasoarous** [comment] 2020-11-16 06:41
Hi again @MawiraIke. Does indeed look like this was fixed with the other issue, so will close this now. Thanks again!

**Closed by metasoarous** 2020-11-16 06:41 UTC
