### ISSUE TITLE
Rendering differences between localhost and online vega-editor

### ISSUE THREAD

**Issue by BorisVSchmid** [metasoarous/oz#12] opened 2018-07-23 14:48 UTC
Hi. 

thanks for picking up vizard and moving it forward.

I have a small example of a world map with a few dots on them. On the plot server, all the dots get plotted in the middle of the screen (just east of Sardinia), while in the vega editor they end up in the correct position (Netherlands).  Any idea what is causing the difference?

`{
  "width": 800,
  "height": 800,
  "layer": [
    {
      "data": {
        "url": "https://gist.githubusercontent.com/almccon/b2d9eaea25b73a16a0ffeb3a2485054c/raw/ce2f85c244be6f0a90f2444080f9d030d1046183/world-50m.json",
        "format": {"type": "topojson", "feature": "countries"}
      },
      "projection": {"type": "orthographic", "rotate": [-10, -40, 0]},
      "mark": {"type": "geoshape", "fill": "lightgrey", "stroke": "white"}
    },
    {
      "data": {
        "values": [
          {"name": "Baarlo", "lng": "5.95", "lat": "52.73833"},
          {"name": "Baarlo", "lng": "6.09444", "lat": "51.33083"},
          {"name": "Hoog-Baarlo", "lng": "5.87639", "lat": "52.10917"},
          {"name": "Baarlo", "lng": "6.10694", "lat": "52.66333"}
        ]
      },
      "projection": {"type": "orthographic", "rotate": [-10, -40, 0]},
      "mark": "circle",
      "encoding": {
        "longitude": {"field": "lng", "type": "quantitative"},
        "latitude": {"field": "lat", "type": "quantitative"},
        "size": {"value": 10},
        "color": {"value": "steelblue"}
      }
    }
  ]
}`

**Comment by metasoarous** [comment] 2018-07-24 18:03
Hi Boris! You're quite welcome; Happy to have you using it!

My guess is that this is something to do with Vega/Vega-Lite versions. Their team has been moving insanely fast, and I've multiple times found bugs in my work on this a few month ago that were resolved by just updating the Vega/Vega-Lite versions.

I'm gonna be giving a talk on Vega/Vega-Lite/Vizard at a local Clojure meetup next week, and there should be a video recording which I'll be able to share. In preparation for that, I'll try to update things. I may not get around to it until this weekend though, so if you feel like testing this hypothesis in the mean time, that would be super helpful.

Cheers

**Comment by metasoarous** [comment] 2018-07-25 16:36
Yes, that all sounds about right. I was actually the last one to update the cljsjs packages. I think the process for doing that could be spelled out a bit better in their docs, but I did manage to get it done.

**Comment by BorisVSchmid** [comment] 2018-08-13 07:27
New vega packages are on cljsjs. I guess that was you! And indeed, updating the project.clj file fixed this issue. 

                 [cljsjs/vega "3.3.1-0"]
                 [cljsjs/vega-lite "2.6.0-0"]
                 [cljsjs/vega-embed "3.16.1-0"]
                 [cljsjs/vega-tooltip "0.12.0-0"]

**Comment by maacl** [comment] 2018-10-07 13:46
Upgrading to the vega packages above gives me the following error in the console:
```
TypeError: vegaTooltip.vegaLite is not a function
    at core.cljs?rel=1537656423194:93
```

**Comment by metasoarous** [comment] 2018-11-09 23:32
Update: I've added some even more recent `cljsjs` updates in flight, so once those hit clojars, I'll mint a new release of oz. Regarding your issue @maacl, I think this is because some of the "extra" vega apis have changed, and calls in oz may need to be updated. Stay tuned, thank you both...

**Comment by realgenekim** [comment] 2018-12-10 05:59
Hi, @metasoarous — wonderful talk at Clojure/conj 2018 about the wonderful work you are doing with polis.  I was delighted to learn at the end that you're the author of oz!

I'm having a problem that I think is similar to this issue.  I successfully create a bunch of graphs, but just recently noticed an oddity.  Vega-lite boxplots only work with `:type "box-plot"`, instead of `:type "boxplot"`.  (It works in the Vega Lite Editor, but not in Oz. https://vega.github.io/editor/#/examples/vega-lite/boxplot_minmax_2D_vertical)

I'd love to know how to get boxplots working in Oz — using "boxplot" as the type results in the following error in the browser console.  

```
Uncaught Error: Unregistered composite mark boxplot
    at Object.n.normalize (oz.js:14)
    at B (oz.js:14)
    at Object.q [as normalize] (oz.js:14)
    at Object.n.compile (oz.js:14)
    at AI (oz.js:1213)
    at Object.<anonymous> (oz.js:1214)
    at Object.<anonymous> (oz.js:608)
    at Object.componentDidMount (oz.js:29)
    at e.notifyAll (oz.js:42)
    at r.close (oz.js:44)
```

I had already updated the project.clj dependencies with the latest cljsjs dependencies:

```
:dependencies [[org.clojure/clojure "1.10.0-RC2"]
                 [org.clojure/tools.cli "0.3.5"]
                 [cljsjs/vega "4.4.0-0"]
                 [cljsjs/vega-lite "3.0.0-rc10-0"]
                 [cljsjs/vega-embed "3.24.1-0"]
                 [cljsjs/vega-tooltip "0.13.0-0"]
                 [metasoarous/oz "1.3.1"]]
```

Here's the odd thing — using "box-plot" as the type works.  Is this a vega-lite v2.0 syntax?  

After hours of poking around, and I may be wildly wrong, but I'm wondering if somehow using an old version of vega-lite, say vega-lite 2.2.0?  (Click on the source file in the console, I found the following string, which I think comes from the compiled.js file in the JAR file?)

```
        7: [function(e, t, n) {
            t.exports = {
                name: "vega-lite",
                author: 'Jeffrey Heer, Dominik Moritz, Kanit "Ham" Wongsuphasawat',
                version: "2.2.0",
```

Many thanks, and keep up the great work!

**Comment by metasoarous** [comment] 2018-12-10 21:58
@realgenekim Thanks for all your poking around here! I think you're right that this is the result of oz being compiled against vega 2, although I was under the impression that modifying your dependency list as you did should have had things load the most recent RC instead of the old v2. I'll do some tinkering around here to see if I can't reproduce that, but long story short is that I have updates on some other issues that I haven't pushed yet, and will try to get a new release minted today which will hopefully resolve this.

**Comment by metasoarous** [comment] 2018-12-11 01:02
@realgenekim @BorisVSchmid There's now a `[metasoarous/oz "1.4.0-SNAPSHOT"]` on Clojars if either of you would be so kind as to test. Pushing changelog updates soon.

**Comment by metasoarous** [comment] 2018-12-11 06:11
Wonderful :-) Again, thanks so much for testing @realgenekim!

I don't know why it was still loading the v2.2 of vega-lite before. It's possible it was just cause of stale js build targets that didn't get regenerated when they were supposed to? I thought that I had run a test to verify that putting the cljsjs deps above `metasoarous/oz` would override the vega/vega-lite versions, and it sounds like @BorisVSchmid got this to work as well, so it must have been something like this. Maybe there's a caveat we don't know about yet.

In any case, glad this is working. Will close this once I get out `1.4.0`.

**Comment by metasoarous** [comment] 2018-12-16 06:16
OK; `1.4.0` is now out.

**Closed by metasoarous** 2018-12-16 06:16 UTC
